services:

  db-temp:
    image: mariadb:11.8
    restart: "no"
    ports:
      - "${MARIADB__EXPOSE_PORT:?}:3306"
    environment:
      MARIADB_USER: ${MARIADB__USER:?}
      MARIADB_PASSWORD: ${MARIADB__PASSWORD:?}
      MARIADB_ROOT_PASSWORD: ${MARIADB__ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB__DATABASE:?}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "-h", "127.0.0.1", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    mem_limit: 256m

  tbls:
    image: ghcr.io/k1low/tbls:latest
    depends_on:
      db-temp:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./doc/database
        target: /work/dbdoc
        read_only: false
      - type: bind
        source: ./.tbls.yml
        target: /work/.tbls.yml
        read_only: true
    working_dir: /work
    command: doc mariadb://${MARIADB__USER:?}:${MARIADB__PASSWORD:?}@db-temp:3306/${MARIADB__DATABASE:?} dbdoc -c .tbls.yml --rm-dist
