services:

  db-dev-adminer:
    image: adminer:5
    restart: "no"
    ports:
      - "3300:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mariadb
      ADMINER_DEFAULT_SERVER: db-dev
    depends_on:
      db-dev:
        condition: service_healthy
    mem_limit: 128m

  db-dev: # Development MariaDB service
    image: mariadb:11.8
    restart: "no"
    ports:
      - "${MARIADB__EXPOSE_PORT:?}:3306"
    environment:
      MARIADB_USER: ${MARIADB__USER:?}
      MARIADB_PASSWORD: ${MARIADB__PASSWORD:?}
      MARIADB_ROOT_PASSWORD: ${MARIADB__ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB__DATABASE:?}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mariadb-admin", "-h", "127.0.0.1", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    mem_limit: 256m

  db-temp: # Temporary MariaDB service for documentation generation
    image: mariadb:11.8
    restart: "no"
    ports:
      - "${MARIADB__EXPOSE_PORT:?}:3306"
    environment:
      MARIADB_USER: ${MARIADB__USER:?}
      MARIADB_PASSWORD: ${MARIADB__PASSWORD:?}
      MARIADB_ROOT_PASSWORD: ${MARIADB__ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB__DATABASE:?}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mariadb-admin", "-h", "127.0.0.1", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    mem_limit: 256m

  tbls:
    image: ghcr.io/k1low/tbls:latest
    depends_on:
      db-temp:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./doc/database
        target: /work/dbdoc
        read_only: false
      - type: bind
        source: ./.tbls.yml
        target: /work/.tbls.yml
        read_only: true
    working_dir: /work
    command: doc mariadb://${MARIADB__USER:?}:${MARIADB__PASSWORD:?}@db-temp:3306/${MARIADB__DATABASE:?} dbdoc -c .tbls.yml --rm-dist
