version: 3

vars:
  DEV_COMPOSE_FILENAME: docker-compose.dev.yml
  DEV_COMPOSE_ENVFILE: .env.dev
  DEV_COMPOSE_SERVICES_APP: app-dev
  DEV_COMPOSE_SERVICES_DB_TEMP: db-temp
  DEV_COMPOSE_SERVICES_DB: db-dev
  DEV_COMPOSE_SERVICES_DB_ADMINER: db-dev-adminer
  DEV_COMPOSE_SERVICES_TBLS: tbls
  STEP_BEGIN: "\e[36;1m"
  STEP_END: "\e[m"

tasks:

  app-down:
    aliases:
      - down
    desc: Stop the development application container and depending services.
    dir: .
    cmd: docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} down

  app-up:
    aliases:
      - up
    desc: Start the development application container and depending services.
    preconditions:
      - sh: ls {{.DEV_COMPOSE_ENVFILE}}
        msg: "required .env file not found: {{.DEV_COMPOSE_ENVFILE}}"
    silent: false
    dir: .
    cmd: docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} up --build -d --wait {{.DEV_COMPOSE_SERVICES_APP}}

  db-down:
    desc: Stop the development database container and Adminer.
    dir: .
    cmd: docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} down {{.DEV_COMPOSE_SERVICES_DB}} {{.DEV_COMPOSE_SERVICES_DB_ADMINER}}

  db-up:
    desc: Start the development database container and Adminer.
    preconditions:
      - sh: ls {{.DEV_COMPOSE_ENVFILE}}
        msg: "required .env file not found: {{.DEV_COMPOSE_ENVFILE}}"
    silent: false
    dir: .
    cmd: docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} up --build -d --wait {{.DEV_COMPOSE_SERVICES_DB}} {{.DEV_COMPOSE_SERVICES_DB_ADMINER}}

  db-docs:
    desc: Generate database documentation using tbls.
    sources:
      - "{{.TASKFILE_DIR}}/.tbls.yml"
      - "{{.TASKFILE_DIR}}/db/init/0_Schema.sql"
    generates:
      - "{{.TASKFILE_DIR}}/doc/database/**"
    run: when_changed
    preconditions:
      - sh: ls {{.DEV_COMPOSE_ENVFILE}}
        msg: "required .env file not found: {{.DEV_COMPOSE_ENVFILE}}"
    silent: false
    dir: .
    cmds:
      - defer: docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} down {{.DEV_COMPOSE_SERVICES_DB_TEMP}} {{.DEV_COMPOSE_SERVICES_TBLS}}
      - docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} up --build --abort-on-container-exit {{.DEV_COMPOSE_SERVICES_TBLS}}

  default:
    desc: Print list of available tasks.
    silent: true
    cmd: task -l

  ef-scaffold:
    desc: Scaffold a new DbContext and entity types based on the current database schema.
    vars:
      PROJECT_DIR: src/KnoqReminder.Infrastructure
      DESTINATION_DIR: "{{.PROJECT_DIR}}/Database"
    sources:
      - "{{.TASKFILE_DIR}}/db/init/*.sql"
    generates:
      - "{{.TASKFILE_DIR}}/{{.DESTINATION_DIR}}/*.cs"
    dir: .
    dotenv:
      - "{{.DEV_COMPOSE_ENVFILE}}"
    preconditions:
      - sh: ls {{.DEV_COMPOSE_ENVFILE}}
        msg: "required .env file not found: {{.DEV_COMPOSE_ENVFILE}}"
      - sh: dotnet --version
        msg: dotnet command not found.
      - sh: dotnet ef --version
        msg: Entity Framework Core tools for .NET CLI not found.
    silent: true
    cmds:
      - defer: "echo \"{{.STEP_BEGIN}}[4/4] Terminating...{{.STEP_END}}\"
                && docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} down {{.DEV_COMPOSE_SERVICES_DB_TEMP}}"
      - "echo \"{{.STEP_BEGIN}}[1/4] Starting temporary database container...{{.STEP_END}}\""
      - docker compose --env-file {{.DEV_COMPOSE_ENVFILE}} -f {{.DEV_COMPOSE_FILENAME}} up --build -d --wait {{.DEV_COMPOSE_SERVICES_DB_TEMP}}
      - "echo \"{{.STEP_BEGIN}}[2/4] Scaffolding from localhost:$MARIADB__EXPOSE_PORT/$MARIADB__DATABASE{{.STEP_END}}\""
      - |
        dotnet ef dbcontext scaffold \
          "Server=localhost;Port=$MARIADB__EXPOSE_PORT;Database=$MARIADB__DATABASE;User Id=$MARIADB__USER;Password=$MARIADB__PASSWORD;" \
          "MySql.EntityFrameworkCore" \
          --project {{.PROJECT_DIR}} \
          --output-dir Database \
          --context AppDbContext \
          --data-annotations \
          --no-onconfiguring \
          --force
      - "echo \"{{.STEP_BEGIN}}[3/4] Formatting generated code...{{.STEP_END}}\""
      - dotnet format --include {{.DESTINATION_DIR}}/*.cs --severity info

  format:
    aliases:
      - fmt
    desc: Format the codebase.
    dir: .
    cmd: dotnet format --severity info

  lint:
    desc: Lint the codebase.
    dir: .
    cmd: dotnet format --verify-no-changes --severity info
