<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="MySql.EntityFrameworkCore" />
    <PackageReference Include="ZLinq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KnoqReminder.Domain\KnoqReminder.Domain.csproj" />
    <ProjectReference Include="..\KnoqReminder.Utilities\KnoqReminder.Utilities.csproj" />
  </ItemGroup>

</Project>
